# Generated by Django 4.2 on 2023-08-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customuser_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
