# Generated by Django 4.2 on 2023-08-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.ImageField(upload_to='postads/', verbose_name='Изображение'),
        ),
    ]
