# Generated by Django 4.2 on 2023-08-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_ad_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('category1', 'Категория 1'), ('category2', 'Категория 2'), ('category3', 'Категория 3'), ('category4', 'Категория 4'), ('category5', 'Категория 5'), ('category6', 'Категория 6'), ('category7', 'Категория 7')], default='category1', max_length=50),
        ),
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.CharField(choices=[('MT', 'Минская область'), ('BR', 'Брестская область'), ('VG', 'Витебская область'), ('HO', 'Гомельская область'), ('GR', 'Гродненская область'), ('MO', 'Могилевская область'), ('MN', 'Минск')], default='MT', max_length=50),
        ),
        migrations.AddField(
            model_name='ad',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.ImageField(default='postads/default.jpg', upload_to='postads/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
