# Generated by Django 4.2 on 2023-08-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_basket_basketitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('category1', 'обувь'), ('одежда', 'одежда'), ('мебель', 'Категория 3'), ('category4', 'Категория 4'), ('category5', 'Категория 5'), ('category6', 'Категория 6'), ('category7', 'Категория 7')], default='category1', max_length=50),
        ),
    ]
