# Generated by Django 4.2 on 2023-08-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_ad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('обувь', 'обувь'), ('одежда', 'одежда'), ('мебель', 'мебель'), ('автомобиль', 'автомобиль'), ('квартира', 'квартира'), ('игрушки', 'игрушки'), ('развлечения', 'развлечения')], default='category1', max_length=50),
        ),
    ]
