# Generated by Django 4.2 on 2023-08-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
    ]
