# Generated by Django 4.1.11 on 2023-09-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
