# Generated by Django 4.1.11 on 2023-09-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='tel',
            field=models.CharField(default='', max_length=100),
        ),
    ]
