# Generated by Django 4.1.11 on 2023-09-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_messageemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='location',
            field=models.CharField(choices=[('', 'Все регионы'), ('MT', 'Минская область'), ('BR', 'Брестская область'), ('VG', 'Витебская область'), ('HO', 'Гомельская область'), ('GR', 'Гродненская область'), ('MO', 'Могилевская область'), ('MN', 'Минск')], default='MT', max_length=50),
        ),
    ]
